import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Metadata } from "next";
import Loading from "@/components/providers/loading-provider";

// Define local fonts
const helveticaLight = localFont({
  src: "./fonts/helvetica/helvetica-light.ttf",
  variable: "--font-helvetica-light",
});
const helveticaRegular = localFont({
  src: "./fonts/helvetica/Helvetica.ttf",
  variable: "--font-helvetica-regular",
});
const helveticaBold = localFont({
  src: "./fonts/helvetica/Helvetica-Bold.ttf",
  variable: "--font-helvetica-bold",
});
const costaLight = localFont({
  src: "./fonts/costa/CostaPtf-Light.otf",
  variable: "--font-costa-light",
});
const costaRegular = localFont({
  src: "./fonts/costa/CostaPtf-Regular.otf",
  variable: "--font-costa-regular",
});
const costaBold = localFont({
  src: "./fonts/costa/CostaPtf-Bold.otf",
  variable: "--font-costa-bold",
});

// Combine all font variables
const fontVariables = [
  helveticaLight.variable,
  helveticaRegular.variable,
  helveticaBold.variable,
  costaLight.variable,
  costaRegular.variable,
  costaBold.variable,
].join(" ");

export const metadata: Metadata = {
  title: "1 Market Philippines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Loading />
      <body className={`${fontVariables} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster richColors position="bottom-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
